source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.4"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 6.3"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem "rack-cors"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# A fast JSON:API serializer for Ruby Objects [https://github.com/jsonapi-serializer/jsonapi-serializer]
gem "jsonapi-serializer"
# Object-based searching [https://github.com/activerecord-hackery/ransack]
gem "ransack"
# Lightweight, simple and maintained JSON:API support for your next Ruby HTTP API [https://github.com/stas/jsonapi.rb]
gem "jsonapi.rb"
# Rack middleware for blocking & throttling [https://github.com/rack/rack-attack/tree/main]
gem "rack-attack"
# Ruby implementation of GraphQL [https://github.com/rmosolgo/graphql-ruby]
gem "graphql"
# Generate sitemap [https://github.com/kjvarga/sitemap_generator]
gem 'sitemap_generator', '~> 6.3'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[mri mingw x64_mingw]

  # Ruby implementation of GraphQL [https://github.com/rmosolgo/graphql-ruby]
  gem "graphiql-rails", group: :development

  # Load environment variables from `.env` [https://github.com/bkeepers/dotenv]
  gem "dotenv-rails"

  # RSpec for Rails 5+ [https://github.com/rspec/rspec-rails]
  gem "rspec-rails"
  # Seamlessly adds a Swagger to Rails-based API's [https://github.com/rswag/rswag]
  gem 'rswag-specs'
  # Fixtures replacement [https://github.com/thoughtbot/factory_bot_rails]
  gem "factory_bot_rails"
  # Code coverage [https://github.com/simplecov-ruby/simplecov]
  gem "simplecov", require: false

  # Code analyzer and formatter [https://github.com/rubocop/rubocop]
  gem "rubocop"
  # Rubocop extension for rails [https://github.com/rubocop/rubocop-rails]
  gem "rubocop-rails"
  # Code style checking for RSpec files [https://github.com/rubocop/rubocop-rspec]
  gem "rubocop-rspec"
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end
